### ISSUE TITLE
只因屁股

### ISSUE THREAD

**Issue by wyttle** [IceTiki/picbed#1]
清晰度过低 无法扫描
![}W2J~L6LF7V8_W4 K9QFAHU](https://user-images.githubusercontent.com/60177306/197134915-4d35e84f-7b03-4741-8235-6582fd418ed5.png)

**Comment by IceTiki** [comment]
你可以下载图片，然后进行一定的处理（比如windows画图）再尝试扫描

**Comment by wyttle** [comment]
解决
